exp_name: 'bevcar_debug'
max_iters: 75000
log_freq: 1000
shuffle: true
dset: 'trainval'
save_freq: 1000
batch_size: 1
grad_acc: 5
lr: 3e-4
use_scheduler: true
weight_decay: 1e-7
nworkers: 12
data_dir: '/media/HDD1/users/user1/argho/dataset/v1.0-mini'
custom_dataroot: '../../../nuscenes/scaled_images'
log_dir: 'logs_nuscenes_bevcar'
ckpt_dir: 'checkpoints/'
keep_latest: 1
init_dir: ''
ignore_load: null
load_step: false
load_optimizer: false
load_scheduler: false
final_dim: [448, 896]
rand_flip: true
rand_crop_and_resize: true
ncams: 6
nsweeps: 5
encoder_type: 'ConvNeXt'
radar_encoder_type: 'voxel_net'
use_rpn_radar: false
train_task: 'both'
use_radar: false
use_radar_filters: false
use_radar_encoder: false
use_metaradar: false
use_shallow_metadata: false
use_pre_scaled_imgs: false
use_obj_layer_only_on_map: false
init_query_with_image_feats: true
do_rgbcompress: true
do_shuffle_cams: true
use_multi_scale_img_feats: false
num_layers: 6
device_ids: [0]
freeze_convnext: true
do_feat_enc_dec: true
combine_feat_init_w_learned_q: true
model_type: 'transformer'
use_radar_occupancy_map: false
learnable_fuse_query: true
group: 'debug'
notes: 'debug run'
name: 'debug'